// <auto-generated />
using System;
using DigitalArs.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalArs.Infrastructure.Migrations
{
    [DbContext(typeof(DigitalArsDbContext))]
    [Migration("20260903000000_UniqueUserDni")]
    partial class UniqueUserDni
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalArs.Domain.Entities.Account", b =>
                {
                    b.Property<int>("ID_Account")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Account"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_User")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Account");

                    b.HasIndex("ID_User")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            ID_Account = 1,
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ID_User = 1,
                            Name = "Cuenta Admin",
                            Price = 10000m
                        },
                        new
                        {
                            ID_Account = 2,
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ID_User = 2,
                            Name = "Cuenta Juan",
                            Price = 5000m
                        },
                        new
                        {
                            ID_Account = 3,
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ID_User = 3,
                            Name = "Cuenta Maria",
                            Price = 7500m
                        });
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.Role", b =>
                {
                    b.Property<int>("ID_Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Role"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Role");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID_Role = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            ID_Role = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("ID_Transaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Transaction"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date_Transaction")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Account")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID_Transaction");

                    b.HasIndex("Date_Transaction");

                    b.HasIndex("ID_Account");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            ID_Transaction = 1,
                            Amount = 2000m,
                            Date_Transaction = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ID_Account = 2,
                            Type = 0
                        },
                        new
                        {
                            ID_Transaction = 2,
                            Amount = 1500m,
                            Date_Transaction = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ID_Account = 1,
                            Type = 2
                        },
                        new
                        {
                            ID_Transaction = 3,
                            Amount = 1500m,
                            Date_Transaction = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ID_Account = 3,
                            Type = 1
                        });
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.User", b =>
                {
                    b.Property<int>("ID_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_User"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ID_Role")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password_Hasheada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_User");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("ID_Role");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID_User = 1,
                            Alias = "admin.digitalars",
                            DNI = "30111222",
                            Email = "admin@digitalars.com",
                            Full_Name = "Admin Principal",
                            ID_Role = 1,
                            IsActive = true,
                            Password_Hasheada = "$2a$11$4UhybbztKrzx7HvDlvNVaurxyqU5U4hT5.kGJGXzWCtWnKQdTxyQS"
                        },
                        new
                        {
                            ID_User = 2,
                            Alias = "juan.perez",
                            DNI = "35222333",
                            Email = "juan.perez@digitalars.com",
                            Full_Name = "Juan Perez",
                            ID_Role = 2,
                            IsActive = true,
                            Password_Hasheada = "$2a$11$lYxAthsE/KgadR48MPwD7eQJ6o6qGitI5A9fCLXTUhKmimbT6G7Wa"
                        },
                        new
                        {
                            ID_User = 3,
                            Alias = "maria.gomez",
                            DNI = "36333444",
                            Email = "maria.gomez@digitalars.com",
                            Full_Name = "Maria Gomez",
                            ID_Role = 2,
                            IsActive = true,
                            Password_Hasheada = "$2a$11$lYxAthsE/KgadR48MPwD7eQJ6o6qGitI5A9fCLXTUhKmimbT6G7Wa"
                        });
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.Account", b =>
                {
                    b.HasOne("DigitalArs.Domain.Entities.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("DigitalArs.Domain.Entities.Account", "ID_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("DigitalArs.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("ID_Account")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.User", b =>
                {
                    b.HasOne("DigitalArs.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("ID_Role")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.User", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
